"""Public API models. These define the OpenAPI contract in /contracts/gateway.openapi.json
that the Android Retrofit client is written against."""

from __future__ import annotations

import base64
import binascii
import uuid
from datetime import date, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints, field_validator, model_validator

Email = Annotated[
    str,
    StringConstraints(strip_whitespace=True, to_lower=True, min_length=5, max_length=254,
                      pattern=r"^[^@\s]+@[^@\s]+\.[^@\s]+$"),
]
EntryStatus = Literal["ok", "uncertain", "unmatched"]
Source = Literal["text", "voice", "photo"]
MAX_GRAMS = 5000.0


# ---------- auth ----------

class RequestCodeIn(BaseModel):
    email: Email


class VerifyCodeIn(BaseModel):
    email: Email
    code: str = Field(pattern=r"^\d{6}$")


class TokenOut(BaseModel):
    access_token: str
    token_type: Literal["bearer"] = "bearer"
    expires_in: int = Field(description="Seconds until the token expires")


class MeOut(BaseModel):
    email: str
    calorie_goal: int | None = None


class GoalIn(BaseModel):
    calorie_goal: int = Field(description="kcal per day; values below the safety minimum are refused (goal_too_low)")


# ---------- diary ----------

class Per100(BaseModel):
    kcal: float
    protein: float
    fat: float
    carbs: float


class EntryOut(BaseModel):
    id: uuid.UUID
    meal_id: uuid.UUID | None = None
    day: date
    eaten_at: datetime
    position: int = Field(description="Order within one message; sort the diary by (eaten_at, position)")
    name: str
    grams: float
    kcal: float | None = Field(default=None, description="Null when the food was not found (status=unmatched)")
    protein: float | None = None
    fat: float | None = None
    carbs: float | None = None
    per100: Per100 | None = Field(default=None, description="Lets the client rescale offline: value = per100 * grams / 100")
    food_name: str | None = Field(default=None, description="The database food this entry was matched to")
    status: EntryStatus
    confidence: float
    source: Source
    updated_at: datetime
    deleted: bool = False


class PendingQuestionIn(BaseModel):
    question: str = Field(min_length=1, max_length=300)
    target_id: uuid.UUID | None = None


class MessageIn(BaseModel):
    client_id: uuid.UUID = Field(description="Generated by the app; retrying with the same id never applies a message twice")
    text: str | None = Field(default=None, max_length=2000)
    image_base64: str | None = Field(default=None, max_length=6_000_000, description="JPEG/PNG/WebP bytes, base64")
    image_mime: Literal["image/jpeg", "image/png", "image/webp"] = "image/jpeg"
    day: date = Field(description="The user's local date for this entry")
    eaten_at: datetime = Field(description="Local time with UTC offset, e.g. 2026-09-30T08:15:00+03:00")
    source: Source = "text"
    pending_question: PendingQuestionIn | None = Field(
        default=None, description="Send the question the app last showed; the text is then read as its answer"
    )

    @field_validator("text")
    @classmethod
    def _strip(cls, v: str | None) -> str | None:
        v = v.strip() if v else None
        return v or None

    @field_validator("image_base64")
    @classmethod
    def _b64(cls, v: str | None) -> str | None:
        if not v:
            return None
        try:
            base64.b64decode(v, validate=True)
        except (binascii.Error, ValueError) as e:
            raise ValueError("image_base64 is not valid base64") from e
        return v

    @field_validator("eaten_at")
    @classmethod
    def _aware(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError("eaten_at must include a UTC offset")
        return v

    @model_validator(mode="after")
    def _needs_input(self) -> MessageIn:
        if not self.text and not self.image_base64:
            raise ValueError("provide text and/or image_base64")
        return self


class MessageOut(BaseModel):
    entries: list[EntryOut] = Field(description="Entries created or changed by this message, in order")
    removed_ids: list[uuid.UUID] = Field(default_factory=list)
    clarify_question: str | None = Field(default=None, description="At most one short question to show in the chat")
    clarify_target_id: uuid.UUID | None = Field(default=None, description="Entry the question is about, if any")


class EntryPatchIn(BaseModel):
    grams: float | None = Field(default=None, gt=0, le=MAX_GRAMS)
    name: str | None = Field(default=None, min_length=1, max_length=100)

    @model_validator(mode="after")
    def _something(self) -> EntryPatchIn:
        if self.grams is None and self.name is None:
            raise ValueError("provide grams and/or name")
        return self


class WeightIn(BaseModel):
    day: date
    kg: float = Field(ge=20, le=400)


class WeightOut(BaseModel):
    id: uuid.UUID
    day: date
    kg: float
    updated_at: datetime
    deleted: bool = False


class SyncOut(BaseModel):
    server_time: datetime
    next_since: datetime = Field(description="Pass as `since` on the next call. Re-delivered rows are harmless: upsert by id.")
    has_more: bool = Field(description="True when a table hit the page size; call again right away with next_since")
    calorie_goal: int | None = None
    entries: list[EntryOut]
    weights: list[WeightOut]


class SttOut(BaseModel):
    text: str
    language: str
    duration_s: float


# ---------- errors / ops ----------

class ErrorDetail(BaseModel):
    code: str
    message: str


class ErrorResponse(BaseModel):
    error: ErrorDetail


class Health(BaseModel):
    status: str
